<docs>
	<doc for="AccessException.AccessException">
		<overload>
			<para>Initializes a new instance of the <see cref="System.AccessException"/>
 class.</para>
		</overload>
		<summary>
			<para>Initializes a new instance of the <see cref="System.AccessException"/>
 class with default properties.</para>
		</summary>
		<remarks>
			<para>The following table shows the initial property values for an instance of 
    <see cref="System.AccessException"/>.</para>
			<list type="table"><listheader>
					<term>Property</term>
					<description>Value</description>
				</listheader>
				<item>
					<term><see cref="System.Exception.InnerException"/></term>
					<description><see langword="null"/>.</description>
				</item>
				<item>
					<term><see cref="System.Exception.Message"/></term>
					<description>The empty string ("").</description>
				</item>
			</list>
		</remarks>
	</doc>
	<doc for="AccessException.AccessException1">
		<summary>
			<para>Initializes a new instance of the <see cref="System.AccessException"/> class 
    with a specified error message.</para>
		</summary>
		<param name="message">The error message that explains the reason for the exception.</param>
		<remarks>
    The following table shows the initial property values for an instance of
 <see cref="System.AccessException"/>.
    <list type="table"><listheader>
					<term>Property</term>
					<description>Value</description>
				</listheader>
				<item>
					<term><see cref="System.Exception.InnerException"/></term>
					<description><see langword="null"/>.</description>
				</item>
				<item>
					<term><see cref="System.Exception.Message"/></term>
					<description>The error message string.</description>
				</item>
			</list>
		</remarks>
	</doc>
	<doc for="AccessException.AccessException3">
		<summary>
			<para>Initializes a new instance of the <see cref="System.AccessException"/> class 
   with serialized data.</para>
		</summary>
		<param name="info">The object that holds the serialized object data.</param>
		<param name=" context">The contextual information about the source or destination.</param>
		<remarks>
			<para>This constructor is called during deserialization to 
      reconstitute the exception object transmitted over a stream. For more
      information, see <see topic="cpconSerialization"/>.</para>
		</remarks>
	</doc><doc for="AccessException.AccessException2">
		<summary>
			<para>Initializes a new instance of the <see cref="System.AccessException"/> 
class with a specified error message and a reference to the
inner exception that is the cause of this exception.</para>
		</summary>
		<param name="message">The error message that explains the reason for the exception.</param>
		<param name="inner">The exception that is the cause of the current exception. If the <paramref name="inner"/> parameter is not <see langword="null"/>, the current exception is raised in a <see langword="catch"/> block that handles the inner exception.</param>
		<remarks>
			<para>An exception that is thrown as a direct result of a 
      previous exception should include a reference to the previous exception in
      the <see cref="System.Exception.InnerException"/> property. The
   <see cref="System.Exception.InnerException"/> 
   property returns the same value that is passed into the constructor, or
<see langword="null"/> if the <see cref="System.Exception.InnerException"/> 
property does not supply the inner exception value to
the constructor. </para>
			<para>The following table shows the initial property values for an instance of
<see cref="System.AccessException"/>.</para>
			<list type="table"><listheader>
					<term>Property</term>
					<description>Value</description>
				</listheader>
				<item>
					<term><see cref="System.Exception.InnerException"/></term>
					<description>The inner exception reference.</description>
				</item>
				<item>
					<term><see cref="System.Exception.Message"/></term>
					<description>The error message string.</description>
				</item>
			</list>
		</remarks>
	</doc><doc for="AccessException">
		<summary>
			<para>The exception that is thrown when an attempt to access a class
      member fails.</para>
		</summary>
		<remarks>
			<para><see cref="System.AccessExcpetion"/> is the base class for <see cref="System.FieldAccessException"/>,
<see cref="System.MethodAccessException"/>, <see cref="System.MissingMemberException"/>, <see cref="System.MissingMethodException"/>,
   and <see cref="System.MissingFieldException"/>.</para>
			<para><see cref="System.AccessException"/> is thrown by the following methods:</para>
			<see cref="System.Reflection.MethodInfo.Invoke"/> of the <see cref="System.Reflection"/> classes,
<see cref="System.Reflection.FieldInfo.GetValue"/> of the <see cref="System.Reflection.FieldInfo"/>
class, and <see cref="System.Delegate.DynamicInvoke"/> of the <see cref="System.Delegate"/> class.
<para><see cref="System.AccessException"/> uses the HRESULT COR_E_MEMBERACCESS which has the
value 0x8013151A.</para>
			<para><see cref="System.AccessException"/> uses the default <see cref="System.Object.Equals"/> implementation, which supports reference
equality.</para>
			<para>For a list of initial property values for an instance of <see cref="System.AccessException"/>, see
the <see cref="System.AccessException()"/> constructors.</para>
		</remarks>
		<seealso cref="System.Exception"/>
		<seealso topic="cpconHandlingThrowingExceptions"/>
	</doc></docs>
