<docs>
	<doc for="ArithmeticException.ArithmeticException3">
		<summary>
			<para>Initializes a new instance of the <see cref="System.ArithmeticException"/> class with serialized data.</para>
		</summary>
		<param name="info">The object that holds the serialized object data.</param>
		<param name="context">The contextual information about the source or destination.</param>
		<remarks>
			<para>This constructor is called during deserialization to reconstitute the
      exception object transmitted over a stream. For more information, see
   <see topic="cpconSerialization"/>.</para>
		</remarks>
		<seealso topic="cpconSerialization"/>
	</doc><doc for="ArithmeticException.ArithmeticException">
		<overload>
			<para>Initializes a new instance of the
   <see cref="System.ArithmeticException"/> class.</para>
		</overload>
		<summary>
			<para>Initializes a new instance of the
   <see cref="System.ArithmeticException"/> 
   
   class.</para>
		</summary>
		<remarks>
			<para>This constructor initializes the <see cref="System.Exception.Message"/> 
property of the new instance to a system-supplied message that describes the
error, such as "The arithmetic operation is not allowed." This message takes
into account the current system culture.</para>
			<para>The following table shows initial property values for an instance of <see cref="System.ArithmeticException"/>.</para>
			<list type="table"><listheader>
					<term>Property</term>
					<description>Value</description>
				</listheader>
				<item>
					<term><see cref="System.Exception.InnerException"/></term>
					<description><see langword="null"/>.</description>
				</item>
				<item>
					<term><see cref="System.Exception.Message"/></term>
					<description>The localized error message string.</description>
				</item>
			</list>
		</remarks>
	</doc><doc for="ArithmeticException.ArithmeticException1">
		<summary>
			<para>Initializes a new instance of the
   <see cref="System.ArithmeticException"/> class with a specified error message.</para>
		</summary>
		<param name="message">A <see cref="System.String"/> that describes the error.</param>
		<remarks>
			<para>The content of the <paramref name="message"/> parameter is 
   intended to be understood by humans. The caller of this constructor is required
   to ensure that this string has been
   localized for the current system culture.</para>
			<para>The following table shows initial property values for an instance of <see cref="System.ArithmeticException"/>.</para>
			<list type="table"><listheader>
					<term>Property</term>
					<description>Value</description>
				</listheader>
				<item>
					<term><see cref="System.Exception.InnerException"/></term>
					<description>The null reference (<see langword="Nothing"/> in 
Visual Basic).</description>
				</item>
				<item>
					<term><see cref="System.Exception.Message"/></term>
					<description>The error message string.</description>
				</item>
			</list>
		</remarks>
	</doc><doc for="ArithmeticException.ArithmeticException2">
		<summary>
			<para>Initializes a new instance of the <see cref="System.ArithmeticException"/>
class with a specified error message and a reference to the
inner exception that is the cause of this exception.</para>
		</summary>
		<param name="message">The error message that explains the reason for the exception.</param>
		<param name="innerException">The exception that is the cause of the current exception. If the <paramref name="innerException"/> parameter is not a null reference, the current exception is raised in a <see langword="catch"/> block that handles the inner exception.</param>
		<remarks>
			<para>An exception that is thrown as a direct result of a
      previous exception should include a reference to the previous exception in
      the <see cref="System.Exception.InnerException"/> property. The
   <see cref="System.Exception.InnerException"/> property returns 
      the same value that is passed into the constructor, or a null reference
      (<see langword="Nothing"/> in Visual Basic) if the <see cref="System.Exception.InnerException"/>
      property does not supply the inner exception value to
      the constructor. </para>
			<para>The following table shows initial property values for an instance of <see cref="System.ArithmeticException"/>.</para>
			<list type="table"><listheader>
					<term>Property</term>
					<description>Value</description>
				</listheader>
				<item>
					<term><see cref="System.Exception.InnerException"/></term>
					<description>The inner exception reference.</description>
				</item>
				<item>
					<term><see cref="System.Exception.Message"/></term>
					<description>The error message string.</description>
				</item>
			</list>
		</remarks>
		<seealso cref="System.Exception"/>
		<seealso topic="cpconHandlingThrowingExceptions"/>
	</doc><doc for="ArithmeticException">
		<summary>
			<para> The exception that
      is thrown for errors in an arithmetic, casting, or conversion operation.</para>
		</summary>
		<remarks>
			<para><see cref="System.ArithmeticException"/> is
   the base class for <see cref="System.DivideByZeroException"/>, <see cref="System.NotFiniteNumberException"/>, and <see cref="System.OverflowException"/> . In
   general, use one of the derived classes of <see cref="System.ArithmeticException"/> to
   more precisely indicate the exact nature of the error. Throw
   an <see cref="System.ArithmeticException"/> if you are only interested in capturing a general arithmetic
   error.</para>
			<para><see cref="System.ArithmeticException"/> uses the HRESULT COR_E_ARITHMETIC, which has the
value 0x80070216.</para>
			<para>For a list of initial property values for an instance of <see cref="System.ArithmeticException"/>,
see the <see cref="System.ArithmeticException"/> constructors. </para>
		</remarks>
		<seealso cref="System.Exception"/>
		<seealso topic="cpconHandlingThrowingExceptions"/>
	</doc>
</docs>
