<docs>
	<doc for="ContextMarshalException.ContextMarshalException">
		<overload>
			<para>Initializes a new instance of the 
    <see cref="System.ContextMarshalException"/> class.</para>
		</overload>
		<summary>
			<para>Initializes a new instance of the 
    <see cref="System.ContextMarshalException"/> 
    class with default properties.</para>
		</summary>
		<remarks>
			<para>The following table shows the initial property values
       for an instance of <see cref="System.ContextMarshalException"/>.</para>
			<list type="table"><listheader>
					<term>Property</term>
					<description>Value</description>
				</listheader>
				<item>
					<term><see cref="System.Exception.InnerException"/></term>
					<description><see langword="null"/>.</description>
				</item>
				<item>
					<term><see cref="System.Exception.Message"/></term>
					<description>The 
    empty string ("").</description>
				</item>
			</list>
		</remarks>
		<platnote platform="">
		</platnote>
	</doc>
	<doc for="ContextMarshalException.ContextMarshalException1">
		<summary>
			<para>Initializes a new instance of the 
    <see cref="System.ContextMarshalException"/> 
    class with a specified error message.</para>
		</summary>
		<param name="message">The error message that explains the reason for the exception.</param>
		<remarks>
			<para>The following table shows the initial property values
       for an instance of <see cref="System.ContextMarshalException"/>.</para>
			<list type="table"><listheader>
					<term>Property</term>
					<description>Value</description>
				</listheader>
				<item>
					<term><see cref="System.Exception.InnerException"/></term>
					<description><see langword="null"/>.</description>
				</item>
				<item>
					<term><see cref="System.Exception.Message"/></term>
					<description>The
    error message string.</description>
				</item>
			</list>
		</remarks>
		<platnote platform="">
		</platnote>
	</doc>
	<doc for="ContextMarshalException.ContextMarshalException3">
		<summary>
			<para>Initializes a new instance of the <see cref="System.ContextMarshalException"/>
class with serialized data.</para>
		</summary>
		<param name="info">The <see cref="System.Runtime.Serialization.SerializationInfo"/> that holds the serialized object data about the exception being thrown.</param>
		<param name="context">The <see cref="System.Runtime.Serialization.StreamingContext"/> that contains contextual information about the source or destination.</param>
	</doc>
	<doc for="ContextMarshalException.ContextMarshalException2">
		<summary>
			<para>Initializes a new instance of the <see cref="System.ContextMarshalException"/> 
class with a specified error message and a reference to the
inner exception that is the cause of this exception.</para>
		</summary>
		<param name="message">The error message that explains the reason for the exception.</param>
		<param name="inner">The exception that is the cause of the current exception. If the <paramref name="inner"/> parameter is not <see langword="null"/>, the current exception is raised in a <see langword="catch"/> block that handles the inner exception.</param>
		<remarks>
			<para>An exception that is thrown as a direct result of a 
      previous exception should include a reference to the previous exception in
      the <see cref="System.Exception.InnerException"/> property. The
   <see cref="System.Exception.InnerException"/> 
   property returns the same value that is passed into the constructor, or
<see langword="null"/> if the <see cref="System.Exception.InnerException"/> 
property does not supply the inner exception value to
the constructor. </para>
			<para>The following table shows the initial property values for
   an instance of <see cref="System.ContextMarshalException"/>.</para>
			<list type="table"><listheader>
					<term>Property</term>
					<description>Value</description>
				</listheader>
				<item>
					<term><see cref="System.Exception.InnerException"/></term>
					<description>The
   inner exception reference.</description>
				</item>
				<item>
					<term><see cref="System.Exception.Message"/></term>
					<description>The
   error message string.</description>
				</item>
			</list>
		</remarks>
	</doc><doc for="ContextMarshalException">
		<summary>
			<para>The exception that is thrown when an attempt to
      marshal an object across a context boundary fails.</para>
		</summary>
		<remarks>
			<para> Objects can marshal by value or by
      reference. Any attempt to pass a type that cannot be marshaled through a context boundary
      will result in a <see cref="System.ContextMarshalException"/>.</para>
			<para><see cref="System.ContextMarshalException"/> uses the HRESULT COR_E_CONTEXTMARSHAL which has the
   value 0x80131504L.</para>
			<para><see cref="System.ContextMarshalException"/> uses the default <see cref="System.Object.Equals"/> implementation, which supports reference
equality.</para>
			<para>For a list of initial property values for an instance of <see cref="System.ContextMarshalException"/>, see the <see cref="M:System.ContextMarshalException.#ctor"/> 
constructors.</para>
		</remarks>
		<seealso cref="System.Exception"/>
		<seealso topic="cpconHandlingThrowingExceptions"/>
	</doc>
</docs>
