<docs>
	<doc for="ServicedComponentException.strDeactivatedObject">
		<summary>
			<para>[To be supplied.]</para>
		</summary>
	</doc>
	<doc for="ServicedComponentException.ServicedComponentException">
		<overload>
			<para>
       Creates a new ServicedComponentException.
    </para>
		</overload>
		<summary>
			<para>
       Creates
       a new RemotingException
       with its message string set to a default message.
    </para>
		</summary>
	</doc>
	<doc for="ServicedComponentException.ServicedComponentException1">
		<summary>
			<para>
       Creates a new ServicedComponentException with
       its message string set to message passing in the constructor.
    </para>
		</summary>
		<param name="message">
    The message that describes the exception
 </param>
	</doc>
	<doc for="ServicedComponentException.ServicedComponentException3">
		<summary>
			<para>[To be supplied.]</para>
		</summary>
	</doc><doc for="ServicedComponentException.ServicedComponentException2">
		<summary>
			<para>Initializes a new instance of the <see cref="System.ServicedComponentException"/> 
class with a specified error message and a reference to the
inner exception that is the cause of this exception.</para>
		</summary>
		<param name="message">The error message that explains the reason for the exception.</param>
		<param name="innerException">The exception that is the cause of the current exception. If the <paramref name="innerException"/> parameter is not <see langword="null"/>, the current exception is raised in a <see langword="catch"/> block that handles the inner exception.</param>
		<remarks>
			<para>An exception that is thrown as a direct result of a 
      previous exception should include a reference to the previous exception in
      the <see cref="System.Exception.InnerException"/> property. The
   <see cref="System.Exception.InnerException"/> 
   property returns the same value that is passed into the constructor, or
<see langword="null"/> if the <see cref="System.Exception.InnerException"/> 
property does not supply the inner exception value to
the constructor. </para>
			<para>The following table shows the initial property values for an instance of
<see cref="System.ServicedComponentException"/>.</para>
			<list type="table">
				<listheader>
					<term>Property</term>
					<description>Value</description>
				</listheader>
				<item>
					<term><see cref="System.Exception.InnerException"/></term>
					<description>The inner exception reference.</description>
				</item>
				<item>
					<term><see cref="System.Exception.Message"/></term>
					<description>The error message
   string.</description>
				</item>
			</list>
		</remarks>
	</doc><doc for="ServicedComponentException">
		<summary>
			<para> This class is the exception class for servicedComponent. An
      Exception is thrown when something has gone wrong.
      </para>
		</summary>
		<seealso cref="System.Exception"/>
		<seealso topic="cpconHandlingThrowingExceptions"/>
	</doc></docs>
