<docs>
	<doc for="StackOverflowException.StackOverflowException">
		<overload>
			<para>Initializes a new instance of the <see cref="System.StackOverflowException"/> class.</para>
		</overload>
		<summary>
			<para>Initializes a new instance of the <see cref="System.StackOverflowException"/> class, setting 
   the <see cref="System.Exception.Message"/> property of the new instance to a system-supplied
   message that describes the error, such as "The requested operation caused a
   stack overflow." This message takes into account the current system culture.</para>
		</summary>
		<remarks>
			<para>The following table shows the initial property values for an instance of
   <see cref="System.StackOverflowException"/>.</para>
			<list type="table"><listheader>
					<term> Property</term>
					<description>Value</description>
				</listheader>
				<item>
					<term><see cref="System.Exception.InnerException"/></term>
					<description><see langword="null"/>.</description>
				</item>
				<item>
					<term><see cref="System.Exception.Message"/></term>
					<description>The localized error message string.</description>
				</item>
			</list>
		</remarks>
	</doc><doc for="StackOverflowException.StackOverflowException1">
		<summary>
			<para>Initializes a new instance of the <see cref="System.StackOverflowException"/> class with
   a specified error message.</para>
		</summary>
		<param name="message">A <see cref="System.String"/> that describes the error. The content of message is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture.</param>
		<remarks>
			<para>The following table shows the initial property values
      for an instance of <see cref="System.StackOverflowException"/>.</para>
			<list type="table"><listheader>
					<term> Property</term>
					<description>Value</description>
				</listheader>
				<item>
					<term><see cref="System.Exception.InnerException"/></term>
					<description>A 
      null reference (<see langword="Nothing"/> in Visual Basic).</description>
				</item>
				<item>
					<term><see cref="System.Exception.Message"/></term>
					<description>The error message string.</description>
				</item>
			</list>
		</remarks>
	</doc><doc for="StackOverflowException.StackOverflowException2">
		<summary>
			<para>Initializes a new instance of the <see cref="System.StackOverflowException"/>
class with a specified error message and a reference to the
inner exception that is the cause of this exception.</para>
		</summary>
		<param name="message">The error message that explains the reason for the exception.</param>
		<param name="innerException">The exception that is the cause of the current exception. If the <paramref name="innerException"/> parameter is not a null reference (<see langword="Nothing"/> in Visual Basic), the current exception is raised in a <see langword="catch"/> block that handles the inner exception.</param>
		<remarks>
			<para> An exception that is thrown as a direct result of
      a previous exception can include a reference to the previous exception in
      the <see cref="System.Exception.InnerException"/> property. The
   <see cref="System.Exception.InnerException"/> property returns 
      the same value that is passed into the constructor, or a null reference
      (<see langword="Nothing"/> in Visual Basic) if the <see cref="System.Exception.InnerException"/>
      property does not supply the inner exception value to
      the constructor. </para>
			<para> The following table shows the initial property
      values for an instance of <see cref="System.StackOverflowException"/>. </para>
			<list type="table"><listheader>
					<term> Property</term>
					<description>Value</description>
				</listheader>
				<item>
					<term><see cref="System.Exception.InnerException"/></term>
					<description>The inner exception reference.</description>
				</item>
				<item>
					<term><see cref="System.Exception.Message"/></term>
					<description>The error message string.</description>
				</item>
			</list>
		</remarks>
		<seealso cref="System.Exception"/>
		<seealso topic="cpconHandlingThrowingExceptions"/>
	</doc><doc for="StackOverflowException">
		<summary>
			<para> The exception that is thrown when the execution stack overflows by having too many pending method calls. This class cannot
      be inherited.</para>
		</summary>
		<remarks>
			<para><see cref="System.StackOverflowException"/> is thrown for execution stack
   overflow errors, typically in case of a very deep or unbounded recursion.</para>
			<para>The <see cref="System.Reflection.Emit.OpCodes.Localloc"/> Microsoft intermediate language 
(MSIL) instruction throws <see cref="System.StackOverflowException"/>.</para>
			<para><see cref="System.StackOverflowException"/> uses the HRESULT COR_E_STACKOVERFLOW, that has the
value 0x800703E9.</para>
			<para>For a list of initial property values for an instance of <see cref="System.StackOverflowException"/>,
see the <see cref="System.StackOverflowException()"/> constructors.</para>
		</remarks>
		<example>
			<codelink SampleID="System.StackOverflowException" SnippetID="1"/>
		</example>
		<seealso cref="System.Exception"/>
		<seealso topic="cpconHandlingThrowingExceptions"/>
	</doc>
</docs>
