<docs>
	<doc for="WeakReferenceException.WeakReferenceException1">
		<summary>
			<para>Initializes a new instance of the <see cref="System.WeakReferenceException"/> class with a specified error message.</para>
		</summary>
		<param name="message">The error message that explains the reason for the exception.</param>
		<remarks>
			<para>The following table shows the initial property
       values for an instance of <see cref="System.WeakReferenceException"/>.</para>
			<list type="table"><listheader>
					<term> Property</term>
					<description>Value</description>
				</listheader>
				<item>
					<term><see cref="System.Exception.InnerException"/></term>
					<description><see langword="null"/>.</description>
				</item>
				<item>
					<term><see cref="System.Exception.Message"/></term>
					<description>The error message string.</description>
				</item>
			</list>
		</remarks>
	</doc>
	<doc for="WeakReferenceException.WeakReferenceException">
		<overload>
			<para>Initializes a new instance of the <see cref="System.WeakReferenceException"/> class.</para>
		</overload>
		<summary>
			<para>Initializes a new instance of the <see cref="System.WeakReferenceException"/> class with default properties.</para>
		</summary>
		<remarks>
			<para>The following table shows the initial property
      values for an instance of <see cref="System.WeakReferenceException"/>.</para>
			<list type="table"><listheader>
					<term> Property</term>
					<description>Value</description>
				</listheader>
				<item>
					<term><see cref="System.Exception.InnerException"/></term>
					<description><see langword="null"/>.</description>
				</item>
				<item>
					<term><see cref="System.Exception.Message"/></term>
					<description>The localized error message string.</description>
				</item>
			</list>
		</remarks>
	</doc><doc for="WeakReferenceException.WeakReferenceException2">
		<summary>
			<para>Initializes a new instance of the <see cref="System.WeakReferenceException"/>
class with a specified error message and a reference to the inner exception that is the root cause of this
exception.</para>
		</summary>
		<param name="message">The error message that explains the reason for the exception.</param>
		<param name="inner">A reference to the inner exception.</param>
		<remarks>
			<para>When handling exceptions, it is useful to capture a 
      series of related exceptions, with the outer exception being thrown in response to an inner exception. The code that handles the second exception
      can use the information from the earlier exception to handle the error
      more appropriately. </para>
			<para>A reference to the inner exception that causes the outer exception is
      available from the <see cref="System.Exception.InnerException"/> property of the outer exception. This exception-linking
      mechanism preserves the error information carried by earlier exceptions,
      including the original exception, while allowing you to create more meaningful
      outer exceptions. For more information, see <see cref="System.Exception"/>.</para>
			<para>The following table shows the initial property values for an instance of
   <see cref="System.WeakReferenceException"/>.</para>
			<list type="table"><listheader>
					<term> Property</term>
					<description>Value</description>
				</listheader>
				<item>
					<term><see cref="System.Exception.InnerException"/></term>
					<description>The inner exception reference.</description>
				</item>
				<item>
					<term><see cref="System.Exception.Message"/></term>
					<description>The error message string.</description>
				</item>
			</list>
		</remarks>
		<seealso cref="System.Exception"/>
		<seealso topic="cpconHandlingThrowingExceptions"/>
	</doc><doc for="WeakReferenceException">
		<summary>
			<para> The exception that is thrown when there is an attempt to
      access an object using a weak reference that is no longer valid.</para>
		</summary>
		<remarks>
			<para><see cref="System.WeakReferenceException"/> is thrown if there is an attempt to access an object
   after its reference is deleted by a call to <see cref="System.Object.Finalize"/>. For more
   information, see <see cref="System.Object"/> and
<see cref="System.WeakReference"/>.</para>
			<para><see cref="System.WeakReferenceException"/> uses the HRESULT COR_E_WEAKREFERENCE, which has the value
0x80131525.</para>
			<para>For a list of initial property values for an instance of <see cref="System.WeakReferenceException"/>,
see the <see cref="System.WeakReferenceException()"/> constructors.</para>
		</remarks>
		<seealso cref="System.Exception"/>
		<seealso topic="cpconHandlingThrowingExceptions"/>
	</doc><doc for="WeakReferenceException.WeakReferenceException3">
		<summary>
			<para>Initialize a new instance of the <see cref="System.WeakReferenceException"/>
class with serialized data.</para>
		</summary>
		<param name="info">The object that holds the serialized object data.</param>
		<param name="context">The contextual information about the source or destination.</param>
		<remarks>
			<para>This constructor is called during deserialization to 
      reconstitute the exception object transmitted over a stream. For more
      information, see <see topic="cpconSerialization"/>.</para>
		</remarks>
		<seealso topic="cpconSerialization"/>
	</doc></docs>
