<docs>
	<doc for="FileNotFoundException">
		<summary>
			<para>The exception that is thrown when an attempt to access a
      file that does not exist on disk fails.</para>
		</summary>
		<remarks>
			<para><see langword="FileNotFoundException"/> uses the HRESULT COR_E_FILENOTFOUND
   which has the value 0x80070002.</para>
		</remarks>
		<seealso cref="System.Exception"/>
		<seealso topic="cpconHandlingThrowingExceptions"/>
		<seealso topic="cpconworkingwithio"/>
		<seealso topic="cpconreadingtextfromfile"/>
		<seealso topic="cpconwritingtexttofile"/>
	</doc>
	<doc for="FileNotFoundException.FileNotFoundException">
		<overload>
			<para>Initializes a new instance of the
   <see cref="System.IO.FileNotFoundException"/> class with optional message string and
      inner <see langword="Exception"/> reference.</para>
		</overload>
		<summary>
			<para>Initializes a new instance of the
   <see cref="System.IO.FileNotFoundException"/> class with its message string
      set to a system-supplied message and its HRESULT set to COR_E_FILENOTFOUND.</para>
		</summary>
		<remarks>
			<para>This
      constructor initializes the <see cref="System.IO.FileNotFoundException.Message"/>
      property of the new instance to a system-supplied message that describes the
      error, such as "Could not find the specified file." This message takes into
      account the current system culture.</para>
		</remarks>
		<seealso topic="cpconworkingwithio"/>
		<seealso topic="cpconreadingtextfromfile"/>
		<seealso topic="cpconwritingtexttofile"/>
	</doc>
	<doc for="FileNotFoundException.FileNotFoundException1">
		<summary>
			<para>Initializes a new instance of the
   <see cref="System.IO.FileNotFoundException"/> class with its message string set to <paramref name="message"/>
   and its HRESULT set
   to COR_E_FILENOTFOUND.</para>
		</summary>
		<param name="message">A <see cref="System.String"/> that describes the error. The content of <paramref name="message"/> is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture.</param>
		<remarks>
			<para>This
      constructor initializes the <see cref="System.IO.FileNotFoundException.Message"/>
      property of the new instance using <paramref name="message"/>.</para>
		</remarks>
		<seealso topic="cpconworkingwithio"/>
		<seealso topic="cpconreadingtextfromfile"/>
		<seealso topic="cpconwritingtexttofile"/>
	</doc>
	<doc for="FileNotFoundException.FileNotFoundException2">
		<summary>
			<para>Initializes a new instance of the <see cref="System.IO.FileNotFoundException"/>
class with a specified error message and a reference to the
inner exception that is the cause of this exception.</para>
		</summary>
		<param name="message">A <see cref="System.String"/> that describes the error. The content of <paramref name="message"/> is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture.</param>
		<param name="innerException">The exception that is the cause of the current exception. If the <paramref name="innerException"/> parameter is not <see langword="null"/>, the current exception is raised in a <see langword="catch"/> block that handles the inner exception.</param>
		<remarks>
			<para>An exception that is thrown as a direct result of a
      previous exception should include a reference to the previous exception in
      the <see cref="System.Exception.InnerException"/> property. The
   <see cref="System.Exception.InnerException"/>
   property returns the same value that is passed into the constructor, or
<see langword="null"/> if the <see cref="System.Exception.InnerException"/> 
property does not supply the inner exception value to
the constructor. </para>
			<para>The following table shows the initial property values for an instance of <see cref="System.IO.FileNotFoundException"/>.</para>
			<list type="table"><listheader>
					<term>Property</term>
					<description>Value</description>
				</listheader>
				<item>
					<term><see cref="System.Exception.InnerException"/></term>
					<description>The inner exception reference.</description>
				</item>
				<item>
					<term><see cref="System.Exception.Message"/></term>
					<description>The error message string.</description>
				</item>
			</list>
For
more information on inner exceptions, see
<see cref="System.Exception.InnerException"/>.
</remarks>
		<seealso cref="System.Exception"/>
		<seealso topic="cpconHandlingThrowingExceptions"/>
		<seealso topic="cpconworkingwithio"/>
		<seealso topic="cpconreadingtextfromfile"/>
		<seealso topic="cpconwritingtexttofile"/>
	</doc>
	<doc for="FileNotFoundException.FileNotFoundException3">
		<summary>
			<para>Initializes a new instance of the <see cref="System.IO.FileNotFoundException"/>
class with its message string set to <paramref name="message"/>, specifying the file name that cannot be found, and its HRESULT set to COR_E_FILENOTFOUND.</para>
		</summary>
		<param name="message">A <see cref="System.String"/> that describes the error. The content of <paramref name="message"/> is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture.</param>
		<param name=" fileName">A <see cref="System.String"/> containing the full name of the file with the invalid image.</param>
		<remarks>
			<para>The
      constructor initializes the <see cref="System.IO.FileNotFoundException.Message"/>
      property of the new instance using <paramref name="message"/> and the
      <see cref="System.IO.FileNotFoundException.FileName"/> property using
      <paramref name="fileName"/>.</para>
		</remarks>
		<seealso topic="cpconworkingwithio"/>
		<seealso topic="cpconreadingtextfromfile"/>
		<seealso topic="cpconwritingtexttofile"/>
	</doc>
	<doc for="FileNotFoundException.FileNotFoundException4">
		<summary>
			<para>Initializes a new instance of the <see cref="System.IO.FileNotFoundException"/>
class with a specified error message and a reference to the
inner exception that is the cause of this exception.</para>
		</summary>
		<param name="message">The error message that explains the reason for the exception.</param>
		<param name="fileName">A <see cref="System.String"/> containing the full name of the file with the invalid image.</param>
		<param name="innerException">The exception that is the cause of the current exception. If the <paramref name="innerException"/> parameter is not <see langword="null"/>, the current exception is raised in a <see langword="catch"/> block that handles the inner exception.</param>
		<remarks>
			<para>An exception that is thrown as a direct result of a
      previous exception should include a reference to the previous exception in
      the <see cref="System.Exception.InnerException"/> property. The
      <see cref="System.Exception.InnerException"/>
   property returns the same value that is passed into the constructor, or
<see langword="null"/> if the <see cref="System.Exception.InnerException"/> 
property does not supply the inner exception value to
the constructor. </para>
			<para>The following table shows the initial property values for an instance of <see cref="System.IO.FileNotFoundException"/>.</para>
			<list type="table"><listheader>
					<term>Property</term>
					<description>Value</description>
				</listheader>
				<item>
					<term><see cref="System.Exception.InnerException"/></term>
					<description>The inner exception reference.</description>
				</item>
				<item>
					<term><see cref="System.Exception.Message"/></term>
					<description>The error message string.</description>
				</item>
			</list>
For
more information on inner exceptions, see
<see cref="System.Exception.InnerException"/>.
</remarks>
		<seealso cref="System.Exception"/>
		<seealso topic="cpconHandlingThrowingExceptions"/>
		<seealso topic="cpconworkingwithio"/>
		<seealso topic="cpconreadingtextfromfile"/>
		<seealso topic="cpconwritingtexttofile"/>
	</doc>
	<doc for="FileNotFoundException.Message">
		<summary>
			<para>Gets the error message that explains the reason for the exception.</para>
		</summary>
		<value>
			<para>A string containing the error message.</para>
		</value>
		<remarks>
			<para>If no message was supplied to the constructor for the current exception, this
      property returns a system-supplied error message. If the <see cref="System.IO.FileLoadException.FileName"/>
      property is not <see langword="null"/>
      , the message includes the file name.</para>
			<para>This property is read-only.</para>
		</remarks>
		<seealso topic="cpconworkingwithio"/>
		<seealso topic="cpconreadingtextfromfile"/>
		<seealso topic="cpconwritingtexttofile"/>
	</doc>
	<doc for="FileNotFoundException.FileName">
		<summary>
			<para>Gets the name of the file that cannot be found.</para>
		</summary>
		<value>
			<para>A
   <see cref="System.String"/> containing the name of the file, or <see langword="null"/> if no file
      name was passed to the constructor for this instance.</para>
		</value>
		<remarks>
			<para>This property is read-only.</para>
		</remarks>
		<seealso topic="cpconworkingwithio"/>
		<seealso topic="cpconreadingtextfromfile"/>
		<seealso topic="cpconwritingtexttofile"/>
	</doc>
	<doc for="FileNotFoundException.ToString">
		<summary>
			<para>Returns the fully qualified name of this exception and possibly the error
      message, the name of the inner exception, and the stack trace. </para>
		</summary>
		<returns>
			<para>A string containing the fully qualified name of this exception and possibly
      the error message, the name of the inner exception, and the stack trace. </para>
		</returns>
		<remarks>
			<para>This
      method overrides <see cref="System.Object.ToString"/>.</para>
			<para>The string representation returned by this method includes the name of the
      exception, the value of the <see cref="System.IO.FileNotFoundException.Message"/> property, the result of calling
      ToString on the inner exception, the value of the <see cref="System.IO.FileNotFoundException.FileName"/> property, and the result of
      calling <see cref="System.Environment.StackTrace"/> . If any of these members is a null
      reference, its value is not included in the returned string.</para>
		</remarks>
		<seealso topic="cpconworkingwithio"/>
		<seealso topic="cpconreadingtextfromfile"/>
		<seealso topic="cpconwritingtexttofile"/>
	</doc>
	<doc for="FileNotFoundException.FileNotFoundException5">
		<summary>
			<para>Initializes a new instance of the <see cref="System.IO.FileNotFoundException"/>
class with the specified serialization and context information.</para>
		</summary>
		<param name="info">The data for serializing or deserializing the file.</param>
		<param name="context">The source and destination for the file.</param>
		<remarks>
		</remarks>
		<seealso topic="cpconworkingwithio"/>
		<seealso topic="cpconreadingtextfromfile"/>
		<seealso topic="cpconwritingtexttofile"/>
	</doc>
	<doc for="FileNotFoundException.FusionLog">
		<summary>
			<para>Gets the log file that describes why loading of an assembly failed.</para>
		</summary>
		<value>
			<para>A <see langword="String"/>
containing errors reported by the assembly cache.</para>
		</value>
		<exception cref="System.Security.SecurityException">The caller does not have the required permission.</exception>
		<remarks>
		</remarks>
		<permission cref="System.Security.Permissions.SecurityPermission">to provide evidence and view and modify policy. Associated enumerations: <see cref="System.Security.Permissions.SecurityPermissionFlag.ControlEvidence" qualify="true"/>, <see cref="System.Security.Permissions.SecurityPermissionFlag.ControlPolicy" qualify="true"/>.</permission>
		<seealso topic="cpconworkingwithio"/>
		<seealso topic="cpconreadingtextfromfile"/>
		<seealso topic="cpconwritingtexttofile"/>
	</doc>
	<doc for="FileNotFoundException.GetObjectData">
		<summary>
			<para>Sets the <see cref="System.Runtime.Serialization.SerializationInfo"/> object with
   the file name and additional exception information.</para>
		</summary>
		<param name="info">The <see cref="System.Runtime.Serialization.SerializationInfo"/> that holds the serialized object data about the exception being thrown.</param>
		<param name=" context">The <see cref="System.Runtime.Serialization.StreamingContext"/> that contains contextual information about the source or destination.</param>
		<remarks>
		</remarks>
		<seealso topic="cpconworkingwithio"/>
		<seealso topic="cpconreadingtextfromfile"/>
		<seealso topic="cpconwritingtexttofile"/>
	</doc>
</docs>
