<docs>
	<doc for="ExternalException.ExternalException">
		<overload>
			<para>Initializes a new instance of the
 <see langword="ExternalException"/>
 class.</para>
		</overload>
		<summary>
			<para>Initializes a new instance of the
 <see langword="ExternalException"/> class with default properties.</para>
		</summary>
		<remarks>
			<para>The following table shows the initial property values
 for an instance of <see langword="ExternalException"/>.
 </para>
			<list type="table"><listheader>
					<term> Property</term>
					<description>Value</description>
				</listheader>
				<item>
					<term><see cref="System.Exception.InnerException"/></term>
					<description><see langword="null"/>.</description>
				</item>
				<item>
					<term><see cref="System.Exception.Message"/></term>
					<description>A
 localized error message string.</description>
				</item>
			</list>
		</remarks>
	</doc><doc for="ExternalException.ExternalException1">
		<summary>
			<para>Initializes a new instance of the
 <see langword="ExternalException"/> class with a specified error message.</para>
		</summary>
		<param name="message">The error message that specifies the reason for the exception.</param>
		<remarks>
			<para>The following table shows the initial property values
 for an instance of <see langword="ExternalException"/>.</para>
			<list type="table"><listheader>
					<term> Property</term>
					<description>Value</description>
				</listheader>
				<item>
					<term><see cref="System.Exception.InnerException"/></term>
					<description><see langword="null"/>.</description>
				</item>
				<item>
					<term><see cref="System.Exception.Message"/></term>
					<description><paramref name="message"/></description>
				</item>
			</list>
		</remarks>
	</doc><doc for="ExternalException.ExternalException3">
		<summary>
			<para>Initializes a new instance of the
 <see langword="ExternalException"/>
 class with
 a
 specified error message and the HRESULT of the error.</para>
		</summary>
		<param name="message">The error message that specifies the reason for the exception.</param>
		<param name="errorCode">The HRESULT of the error.</param>
		<remarks>
			<para>The following table shows the initial property values
 for an instance of <see langword="ExternalException"/>.</para>
			<list type="table"><listheader>
					<term>Property</term>
					<description>Value</description>
				</listheader>
				<item>
					<term><see cref="System.Runtime.InteropServices.ExternalException.ErrorCode"/></term>
					<description>The HRESULT of the error.</description>
				</item>
				<item>
					<term><see cref="System.Exception.InnerException"/></term>
					<description><see langword="null"/>
					</description>
				</item>
				<item>
					<term><see cref="System.Exception.Message"/></term>
					<description><paramref name="message"/></description>
				</item>
			</list>
		</remarks>
	</doc><doc for="ExternalException.ExternalException4">
		<summary>
			<para>Initializes a new instance of the
 <see langword="ExternalException"/>
 class from serialization data.</para>
		</summary>
		<param name="info">The object that holds the serialized object data.</param>
		<param name=" context">The contextual information about the source or destination.</param>
		<exception cref="System.ArgumentNullException"><paramref name="info"/> is <see langword="null"/> .</exception>
		<remarks>
			<para>This constructor is called during deserialization to
 reconstitute the exception object transmitted over a stream. For more
 information, see <see topic="cpconSerialization"/>.</para>
		</remarks>
	</doc><doc for="ExternalException.ErrorCode">
		<summary>
			<para> Gets the HRESULT of the error.</para>
		</summary>
		<value>
			<para> 
 The HRESULT of the error.</para>
		</value>
	</doc><doc for="ExternalException.ExternalException2">
		<summary>
			<para>Initializes a new instance of the <see cref="System.Runtime.InteropServices.ExternalException"/>
class with a specified error message and a reference to the
inner exception that is the cause of this exception.</para>
		</summary>
		<param name="message">The error message that explains the reason for the exception.</param>
		<param name="inner">The exception that is the cause of the current exception. If the <paramref name="inner"/> parameter is not <see langword="null"/>, the current exception is raised in a <see langword="catch"/> block that handles the inner exception.</param>
		<remarks>
			<para>An exception that is thrown as a direct result of a
      previous exception should include a reference to the previous exception in
      the <see cref="System.Exception.InnerException"/> property. The
   <see cref="System.Exception.InnerException"/>
   property returns the same value that is passed into the constructor, or
<see langword="null"/> if the <see cref="System.Exception.InnerException"/> 
property does not supply the inner exception value to
the constructor. </para>
			<para>The following table shows the initial property values for an instance of <see cref="System.Runtime.InteropServices.ExternalException"/>.</para>
			<list type="table"><listheader>
					<term>Property</term>
					<description>Value</description>
				</listheader>
				<item>
					<term><see cref="System.Exception.InnerException"/></term>
					<description>The inner exception reference.</description>
				</item>
				<item>
					<term><see cref="System.Exception.Message"/></term>
					<description>The error message string.</description>
				</item>
			</list>
		</remarks>
		<seealso cref="System.Exception"/>
		<seealso topic="cpconHandlingThrowingExceptions"/>
	</doc><doc for="ExternalException">
		<summary>
			<para> The base exception type for all COM interop exceptions
      and structured exception handling (SEH) exceptions.</para>
		</summary>
		<remarks>
			<para> To
      enhance interoperability between legacy systems and the common language runtime,
      the <see cref="System.Runtime.InteropServices.ExternalException.ErrorCode"/>
      property stores an integer value (HRESULT) that identifies the
      error. User defined exceptions should never derive from
   <see langword="ExternalException"/>, and an <see langword="ExternalException"/>
   should never be thrown by user code. Use the specific exceptions that derive
   from <see langword="ExternalException"/> instead.</para>
			<para><see langword="ExternalException"/> uses the HRESULT
E_FAIL which has the
value 0x80004005.</para>
			<para><see langword="ExternalException"/> uses the default <see cref="System.Object.Equals"/> implementation, which
supports reference equality.</para>
			<para>For a list of initial values for an instance of
<see langword="ExternalException"/>, see 
   the <see langword="ExternalException"/> constructors.</para>
		</remarks>
		<seealso cref="System.Exception"/>
		<seealso topic="cpconHandlingThrowingExceptions"/>
	</doc></docs>
