<docs>
	<doc for="SafeArrayRankMismatchException">
		<summary>
			<para>The exception thrown when the rank of an incoming <see langword="SAFEARRAY"/> does
   not match the rank specified in the managed signature.</para>
		</summary>
		<remarks>
			<para><see langword="SafeArrayRankMismatchException"/> uses the HRESULT
   COR_E_SAFEARRAYRANKMISMATCH which has the value 0x80131538.</para>
			<para>The rank of a <see langword="SAFEARRAY"/> is the number of dimensions in
that array.</para>
		</remarks>
		<seealso cref="System.Exception"/>
		<seealso topic="cpconHandlingThrowingExceptions"/>
	</doc><doc for="SafeArrayRankMismatchException.SafeArrayRankMismatchException2">
		<summary>
			<para>Initializes a new instance of the <see cref="System.Runtime.InteropServices.SafeArrayRankMismatchException"/>
class with a specified error message and a reference to the
inner exception that is the cause of this exception.</para>
		</summary>
		<param name="message">The error message that explains the reason for the exception.</param>
		<param name="inner">The exception that is the cause of the current exception. If the <paramref name="inner"/> parameter is not <see langword="null"/>, the current exception is raised in a <see langword="catch"/> block that handles the inner exception.</param>
		<remarks>
			<para>An exception that is thrown as a direct result of a
      previous exception should include a reference to the previous exception in
      the <see cref="System.Exception.InnerException"/> property. The
   <see cref="System.Exception.InnerException"/>
   property returns the same value that is passed into the constructor, or
<see langword="null"/> if the <see cref="System.Exception.InnerException"/> 
property does not supply the inner exception value to
the constructor. </para>
			<para>The following table shows the initial property values for an instance of <see cref="System.Runtime.InteropServices.SafeArrayRankMismatchException"/>.</para>
			<list type="table"><listheader>
					<term>Property</term>
					<description>Value</description>
				</listheader>
				<item>
					<term><see cref="System.Exception.InnerException"/></term>
					<description>The inner exception reference.</description>
				</item>
				<item>
					<term><see cref="System.Exception.Message"/></term>
					<description>The error message string.</description>
				</item>
			</list>
		</remarks>
		<seealso cref="System.Exception"/>
		<seealso topic="cpconHandlingThrowingExceptions"/>
	</doc><doc for="SafeArrayRankMismatchException.SafeArrayRankMismatchException">
		<overload>
			<para>Initializes a new instance
      of the <see langword="SafeArrayRankMismatchException "/>class.</para>
		</overload>
		<summary>
			<para>Initializes a new instance of the
   <see langword="SafeArrayTypeMismatchException "/>class with default values.</para>
		</summary>
		<remarks>
			<para><see langword="SafeArrayRankMismatchException "/>inherits from <see cref="System.SystemException"/>. This
   constructor sets the properties of the <see cref="System.Exception"/> object as shown in the following
   table.</para>
			<list type="table">
				<listheader>
					<term>Property</term>
					<description>Value</description>
				</listheader>
				<item>
					<term><see cref="System.Exception.InnerException"/></term>
					<description><see langword="null"/>.</description>
				</item>
				<item>
					<term><see cref="System.Exception.Message"/></term>
					<description>A localized error message
   string.</description>
				</item>
			</list>
		</remarks>
	</doc><doc for="SafeArrayRankMismatchException.SafeArrayRankMismatchException1">
		<summary>
			<para>Initializes a new instance of the
   <see langword="SafeArrayRankMismatchException"/> class with the specified message.</para>
		</summary>
		<param name="message">The message that indicates the reason for the exception.</param>
		<remarks>
			<para><see langword="SafeArrayRankMismatchException "/>inherits from <see cref="System.SystemException"/>. This
   constructor sets the properties of the <see cref="System.Exception"/> object as shown in the following
   table.</para>
			<list type="table">
				<listheader>
					<term>Property</term>
					<description>Value</description>
				</listheader>
				<item>
					<term><see cref="System.Exception.InnerException"/></term>
					<description><see langword="null"/>.</description>
				</item>
				<item>
					<term><see cref="System.Exception.Message"/></term>
					<description><paramref name="message"/></description>
				</item>
			</list>
		</remarks>
	</doc><doc for="SafeArrayRankMismatchException.SafeArrayRankMismatchException3">
		<summary>
			<para>Initializes a new instance of the
   <see langword="SafeArrayTypeMismatchException"/> class from serialization
      data.</para>
		</summary>
		<param name="info">The object that holds the serialized object data.</param>
		<param name=" context">The contextual information about the source or destination.</param>
		<exception cref="System.ArgumentNullException"><paramref name="info"/> is <see langword="null"/>.</exception>
		<remarks>
			<para>This constructor is called during deserialization to
      reconstitute the exception object transmitted over a stream. For more
      information, see <see cref="System.Runtime.Serialization"/>.</para>
			<para><see langword="SafeArrayRankMismatchException "/>inherits from <see cref="System.SystemException"/>.</para>
		</remarks>
	</doc></docs>
