<docs>
	<doc for="SEHException.CanResume">
		<summary>
			<para>Indicates whether the exception can be recovered from or 
      not, and if the code can continue from the point where the exception was thrown.</para>
		</summary>
		<returns>
			<para>Resumable exceptions are not yet implemented, so this
      method always returns <see langword="false"/>
      .</para>
		</returns>
		<remarks>
			<see cref="System.Runtime.InteropServices.SEHException.CanResume"/> can be resumable, 
   which means a filtered exception handler can correct the problem that caused the
   exception, and the code will continue from the point that threw the exception.
</remarks>
	</doc><doc for="SEHException">
		<summary>
			<para>Represents Structured Exception Handler (SEH) errors.</para>
		</summary>
		<remarks>
			<para>The <see langword="SEHException"/> class
   handles errors from the SEH code.</para>
			<para><see langword="SEHException"/> uses the HRESULT E_FAIL which has the value
0x80004005.</para>
		</remarks>
		<seealso cref="System.Exception"/>
		<seealso topic="cpconHandlingThrowingExceptions"/>
	</doc><doc for="SEHException.SEHException2">
		<summary>
			<para>Initializes a new instance of the <see cref="System.Runtime.InteropServices.SEHException"/>
class with a specified error message and a reference to the
inner exception that is the cause of this exception.</para>
		</summary>
		<param name="message">The error message that explains the reason for the exception.</param>
		<param name="inner">The exception that is the cause of the current exception. If the <paramref name="inner"/> parameter is not <see langword="null"/>, the current exception is raised in a <see langword="catch"/> block that handles the inner exception.</param>
		<remarks>
			<para>An exception that is thrown as a direct result of a
      previous exception should include a reference to the previous exception in
      the <see cref="System.Exception.InnerException"/> property. The
   <see cref="System.Exception.InnerException"/>
   property returns the same value that is passed into the constructor, or
<see langword="null"/> if the <see cref="System.Exception.InnerException"/> 
property does not supply the inner exception value to
the constructor. </para>
			<para>The following table shows the initial property values for an instance of <see cref="System.Runtime.InteropServices.SEHException"/>.</para>
			<list type="table"><listheader>
					<term>Property</term>
					<description>Value</description>
				</listheader>
				<item>
					<term><see cref="System.Exception.InnerException"/></term>
					<description>The inner exception reference.</description>
				</item>
				<item>
					<term><see cref="System.Exception.Message"/></term>
					<description>The error message string.</description>
				</item>
			</list>
		</remarks>
		<seealso cref="System.Exception"/>
		<seealso topic="cpconHandlingThrowingExceptions"/>
	</doc><doc for="SEHException.SEHException">
		<overload>
			<para>Initializes an instance of the
   <see langword="SEHException"/>
   class.</para>
		</overload>
		<summary>
			<para>Initializes an instance of the
   <see langword="SEHException"/>
   with default properties.</para>
		</summary>
		<remarks>
			<para><see langword="SEHException "/>inherits from <see cref="System.Runtime.InteropServices.ExternalException"/>. This constructor sets the
   properties of the <see cref="System.Exception"/> object as shown in the following table.</para>
			<list type="table"><listheader>
					<term>Property Type</term>
					<description>Condition</description>
				</listheader>
				<item>
					<term><see cref="System.Exception.InnerException"/></term>
					<description><see langword="null"/>.</description>
				</item>
				<item>
					<term><see cref="System.Exception.Message"/></term>
					<description>A
   localized error message string.</description>
				</item>
			</list>
		</remarks>
	</doc><doc for="SEHException.SEHException1">
		<summary>
			<para>Initializes a new instance of the
   <see langword="SEHException"/> class with a specified
      message.</para>
		</summary>
		<param name="message">The message that indicates the reason for the exception.</param>
		<remarks>
			<para><see langword="SEHException "/>inherits from <see cref="System.Runtime.InteropServices.ExternalException"/>. This constructor sets the
   properties of the <see cref="System.Exception"/> object as shown in the following table.</para>
			<list type="table"><listheader>
					<term>Property Type</term>
					<description>Condition</description>
				</listheader>
				<item>
					<term><see cref="System.Exception.InnerException"/></term>
					<description><see langword="null"/>.</description>
				</item>
				<item>
					<term><see cref="System.Exception.Message"/></term>
					<description><paramref name="message"/></description>
				</item>
			</list>
		</remarks>
	</doc><doc for="SEHException.SEHException3">
		<summary>
			<para>Initializes a new instance of the <see langword="SEHException"/> class from
   serialization data.</para>
		</summary>
		<param name="info">The object that holds the serialized object data.</param>
		<param name=" context">The contextual information about the source or destination.</param>
		<exception cref="System.ArgumentNullException"><paramref name="info"/> is <see langword="null"/> .</exception>
		<remarks>
			<para>This constructor is called during deserialization to
      reconstitute the exception object transmitted over a stream. For more
      information, see <see cref="System.Runtime.Serialization"/>.</para>
			<para><see langword="SEHException"/> inherits from <see cref="System.Runtime.InteropServices.ExternalException"/> . </para>
		</remarks>
	</doc></docs>
