<docs>
	<doc for="SynchronizationLockException.SynchronizationLockException1">
		<summary>
			<para> Initializes a new instance of the <see cref="System.Threading.SynchronizationLockException"/> class with a specified error message.
   </para>
		</summary>
		<param name="message">The error message that explains the reason for the exception. </param>
		<remarks>
			<para>The following table shows the initial property values for an instance of 
   <see cref="System.Threading.SynchronizationLockException"/>.</para>
			<list type="table">
				<listheader>
					<term> Property</term>
					<description>Value</description>
				</listheader>
				<item>
					<term>
						<see cref="System.Exception.InnerException"/></term>
					<description><see langword="null"/>.</description>
				</item>
				<item>
					<term>
						<see cref="System.Exception.Message"/></term>
					<description> The error message string.</description>
				</item>
			</list>
		</remarks>
	</doc><doc for="SynchronizationLockException.SynchronizationLockException2">
		<summary>
			<para>Initializes a new instance of the <see cref="System.Threading.SynchronizationLockException"/>
class with a specified error message and a reference to the
inner exception that is the cause of this exception.</para>
		</summary>
		<param name="message">The error message that explains the reason for the exception.</param>
		<param name="innerException">The exception that is the cause of the current exception. If the <paramref name="innerException"/> parameter is not <see langword="null"/>, the current exception is raised in a <see langword="catch"/> block that handles the inner exception.</param>
		<remarks>
			<para>An exception that is thrown as a direct result of a
      previous exception should include a reference to the previous exception in
      the <see cref="System.Exception.InnerException"/> property. The
   <see cref="System.Exception.InnerException"/>
   property returns the same value that is passed into the constructor, or
<see langword="null"/> if the <see cref="System.Exception.InnerException"/> 
property does not supply the inner exception value to
the constructor. </para>
			<para>The following table shows the initial property values for an instance of <see cref="System.Threading.SynchronizationLockException"/>.</para>
			<list type="table"><listheader>
					<term>Property</term>
					<description>Value</description>
				</listheader>
				<item>
					<term><see cref="System.Exception.InnerException"/></term>
					<description>The inner exception reference.</description>
				</item>
				<item>
					<term><see cref="System.Exception.Message"/></term>
					<description>The error message string.</description>
				</item>
			</list>
		</remarks>
		<seealso cref="System.Exception"/>
		<seealso topic="cpconHandlingThrowingExceptions"/>
	</doc><doc for="SynchronizationLockException.SynchronizationLockException3">
		<summary>
			<para>Initializes a new instance of the <see cref="System.Threading.SynchronizationLockException"/> class with serialized data.</para>
		</summary>
		<param name="info">The <see cref="System.Runtime.Serialization.SerializationInfo"/> that holds the serialized object data about the exception being thrown.</param>
		<param name="context">The <see cref="System.Runtime.Serialization.StreamingContext"/> that contains contextual information about the source or destination.</param>
		<remarks>
			<para>This constructor is called during deserialization to reconstitute the
      exception object transmitted over a stream. For more information, see
   <see topic="cpconSerialization"/>.</para>
		</remarks>
		<seealso topic="cpconSerialization"/>
	</doc><doc for="SynchronizationLockException.SynchronizationLockException">
		<overload>
			<para> Initializes a new instance of the <see cref="System.Threading.SynchronizationLockException"/> class.
   </para>
		</overload>
		<summary>
			<para> Initializes a new instance of the <see cref="System.Threading.SynchronizationLockException"/> class with default properties.
   </para>
		</summary>
		<remarks>
			<para>The following table shows the initial property values for an instance of
   <see cref="System.Threading.SynchronizationLockException"/>.</para>
			<list type="table">
				<listheader>
					<term> Property</term>
					<description> Value </description>
				</listheader>
				<item>
					<term>
						<see cref="System.Exception.InnerException"/></term>
					<description><see langword="null"/>.</description>
				</item>
				<item>
					<term>
						<see cref="System.Exception.Message"/></term>
					<description> The localized error message string.</description>
				</item>
			</list>
		</remarks>
	</doc>
	<doc for="SynchronizationLockException">
		<summary>
			<para> The exception that is thrown when a method requires the
      caller to own the lock on a given Monitor, and the method is
      invoked by a caller that does not own that lock.
      </para>
		</summary>
		<remarks>
			<para><see cref="System.Threading.SynchronizationLockException"/> is thrown by calling the
<see cref="System.Threading.Monitor.Exit"/>, <see cref="System.Threading.Monitor.Pulse"/>, <see cref="System.Threading.Monitor.PulseAll"/>, and <see cref="System.Threading.Monitor.Wait"/> methods of the 
<see cref="System.Threading.Monitor"/> class from an unsynchronized block of code.
   </para>
			<para><see cref="System.Threading.SynchronizationLockException"/> uses the HRESULT COR_E_SYNCHRONIZATIONLOCK,
which has the value 0x80131518.</para>
			<para>For a list of initial property values for an instance of
<see cref="System.Threading.SynchronizationLockException"/>, see 
   the <see cref="M:System.Threading.SynchronizationLockException.#ctor"/>
   constructors.</para>
		</remarks>
		<seealso cref="System.Threading.Monitor"/>
		<seealso topic="cpconManagedUnmanagedThreading"/>
		<seealso cref="System.Exception"/>
		<seealso topic="cpconHandlingThrowingExceptions"/>
	</doc>
</docs>
